Return value of compare 1 if differences
MeteoSwiss-APN/serialbox pull request #82
Opened 2017-07-14 10:02 UTC by clementval

For integration test, otherwise jenkins thinks everythings is fine :-)

2017-07-14 10:03 UTC, clementval commented
I'll do the change in Serialbox2 as well once this is ok.

2017-07-17 16:11 UTC, havogt requested changes

2017-07-17 16:11 UTC, havogt commented on tools/compare.cpp
>  	// return (int) (!equal);
Can be deleted?

2017-07-17 16:11 UTC, havogt commented on tools/compare.cpp
> +        bool hasDifferences = false;
indendation looks wrong for all the lines which you added.

2017-07-17 18:29 UTC, clementval reviewed
@havogt This file is using sadly using tabs. If you don't mind, I would like to push a commit with changes to spaces instead...

2017-07-17 18:32 UTC, havogt commented
Oh yes of course. I don't want to be responsible that someone's salary has to be cut because of the tabs!

2017-07-18 06:12 UTC, havogt approved these changes
I didn't check all the reformatting...

2017-07-18 08:08 UTC, clementval commented
Thanks! By the way, do we have a code style for serialbox yet?

2017-07-18 08:08 UTC, merged

2017-07-18 08:10 UTC, havogt commented
(For serialbox2 (C++ part) there is a clang-format style file.)

2017-07-18 08:10 UTC, clementval commented
Ok so I suggest that for the old one we don't care too much as we will switch anyway ...